--liquibase formatted sql

--changeset admin:1
CREATE TABLE IF NOT EXISTS users
(
    id                     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username               VARCHAR(50)  NOT NULL UNIQUE,
    email                  VARCHAR(100) NOT NULL UNIQUE,
    password_hash          VARCHAR(255) NOT NULL,
    birth_date             DATE,
    firstname              VARCHAR(64),
    lastname               VARCHAR(64),
    role                   VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    telegram_chat_id       BIGINT,
    notification_enabled   BOOLEAN NOT NULL DEFAULT true
);

--changeset admin:2
CREATE TABLE IF NOT EXISTS reminders
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255)  NOT NULL,
    description     VARCHAR(4096),
    remind_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    type            VARCHAR(50)   NOT NULL DEFAULT 'EMAIL',
    status          VARCHAR(32)   NOT NULL DEFAULT 'PENDING',
    user_id         BIGINT        NOT NULL,
    CONSTRAINT fk_reminders_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

--changeset admin:3
ALTER TABLE reminders DROP COLUMN IF EXISTS remind;
ALTER TABLE reminders
ALTER COLUMN remind_at SET NOT NULL;
